# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dp',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.DepartMent'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '中')], default=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=1, null=True, verbose_name='状态'),
        ),
    ]
